kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.47.0/deploy/static/provider/cloud/deploy.yaml
kubectl apply -f mybroker\deployment\my-broker-deployment.yml
kubectl apply -f pv-local\pv-local.yml 
kubectl apply -f pv-local\images-pvc.yml 
kubectl apply -f pv-local\postgres-pvc.yml 
kubectl apply -f pv-local\postgres-configMap.yml
kubectl apply -f pv-local\postgres-secret.yml 
kubectl apply -f pv-local\postgres-deployment.yml
kubectl apply -f myredis\deployment\my-redis-deployment.yml
kubectl apply -f mycontentdelivery\deployment\my-contentdelivery-deployment.yml
kubectl apply -f myimageuploader\deployment\my-imageuploader-deployment.yml
kubectl apply -f BrightnessVerifier\deployment\my-brightnessverifier-deployment.yml
kubectl apply -f myfrontend\deployment\my-frontend-deployment.yml
kubectl apply -f myingress\my-ingress.yml
