apiVersion: v1
kind: Service
metadata:
  name: myimageuploader
spec:
  ports:
    - port: 5050
      targetPort: 5050
  selector:
    svc: myimageuploader
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myimageuploader
  labels:
    svc: myimageuploader
spec:
  template:
    metadata:
      name: myimageuploader
      labels:
        svc: myimageuploader
    spec:
      volumes:
        - name: incoming
          persistentVolumeClaim:
            claimName: incoming-pvc
        - name: filtered
          persistentVolumeClaim:
            claimName: filtered-pvc
      containers:
        - name: my-imageuploader-container
          image: kkonkol/myimageuploader
          command: ["sh"]
          args: ["-c", "node index.js"]
          ports:
            - containerPort: 5050
          volumeMounts:
            - name: incoming
              mountPath: /opt/app/shared/incoming
            - name: filtered
              mountPath: /opt/app/shared/filtered
  replicas: 1
  selector:
    matchLabels:
      svc: myimageuploader
  
  
  