
apiVersion: v1
kind: Service
metadata:
  name: myapi
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    svc: myapi
---
apiVersion: v1
kind: Pod
metadata:
  name: myapi
  labels:
    svc: myapi
spec: 
  containers:
    - name: myapi
      image: kkonkol/mybackend
      ports: 
        - containerPort: 5000