apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: incoming-pvc

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filtered-pvc

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Mi