apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local3
  labels:
    type: local

spec:
  storageClassName: manual
  capacity:
    storage: 20Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/c/persistance"