apiVersion: v1
kind: Service
metadata:
  name: myredis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    svc: myredis
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: myredis
  labels:
    svc: myredis

spec:
  template:
    metadata:
      name: myredis-pod
      labels:
        svc: myredis
    spec:
      containers:
        - name: myredis-container
          image: redis:alpine
          ports:
            - containerPort: 6379                      
  replicas: 1
  selector:
    matchLabels:
      svc: myredis
